server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 10000
        response-timeout: 30s
      routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**,/api/v1/categories/**,/api/v1/brands/**,/api/v1/public/brands/**,/api/v1/public/categories/**
          filters:
            - AuthenticationFilter

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - AuthenticationFilter

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/notification/**

        - id: identity-service-auth
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/api/v1/auth/**

        - id: identity-service-user
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/api/v1/user/**
          filters:
            - AuthenticationFilter

        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/inventory/**

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payments/**

        - id: customer-service-public
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/v1/public/customer/**

        - id: customer-service-admin
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/v1/customers/**
        - id: product-service-public
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/public/products/**

# Actuator Configuration (for Prometheus)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,caches
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      sla:
        http.server.requests: 10ms,50ms,100ms,200ms,500ms,1s
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

identity:
  jwt:
    secret-key: ${JWT_SECRET_KEY:cb3f30b0ec715f1bcbead50dc9d77786c038b569f2f6adb9a9e724e07ffd6c17}

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG